CREATE TABLE "activities" (
  "resource_state" double precision,
  "athlete.id" double precision,
  "athlete.resource_state" double precision,
  "name" text,
  "distance" double precision,
  "moving_time" double precision,
  "elapsed_time" double precision,
  "total_elevation_gain" double precision,
  "type" text,
  "sport_type" text,
  "workout_type" double precision,
  "id" double precision primary key,
  "start_date" text,
  "start_date_local" text,
  "timezone" text,
  "utc_offset" double precision,
  "location_city" text NULL,
  "location_state" text NULL,
  "location_country" text,
  "achievement_count" double precision,
  "kudos_count" double precision,
  "comment_count" double precision,
  "athlete_count" double precision,
  "photo_count" double precision,
  "map.id" text,
  "map.summary_polyline" text,
  "map.resource_state" double precision,
  "trainer" boolean,
  "commute" boolean,
  "manual" boolean,
  "private" boolean,
  "visibility" text,
  "flagged" boolean,
  "gear_id" text,
  "start_latlng" json,
  "end_latlng" json,
  "average_speed" double precision,
  "max_speed" double precision,
  "average_cadence" double precision,
  "average_temp" double precision,
  "has_heartrate" boolean,
  "average_heartrate" double precision,
  "max_heartrate" double precision,
  "heartrate_opt_out" boolean,
  "display_hide_heartrate_option" boolean,
  "elev_high" double precision,
  "elev_low" double precision,
  "upload_id" double precision,
  "upload_id_str" text,
  "external_id" text,
  "from_accepted_tag" boolean,
  "pr_count" double precision,
  "total_photo_count" double precision,
  "has_kudoed" boolean
);
